services:
  skyfactory5:
    build: .
    container_name: sf5_server
    networks:
      - proxy
    ports:
      # Sol taraf (.env'den gelen) makinenizin portu, sağ taraf (25565) container'ın iç portudur.
      - "${HOST_PORT}:25565"
    volumes:
      - ./data:/server
    environment:
      - SERVER_RAM=${SERVER_RAM}
    stdin_open: true
    tty: true
    restart: unless-stopped

  backup:
    image: alpine:latest
    container_name: sf5_backup
    restart: unless-stopped
    depends_on:
      - skyfactory5
    volumes:
      - ./data:/server:ro
      - ./backups:/backups
    # Script içerisindeki ayarları doğrudan .env dosyasından çekiyoruz
    command: >
      /bin/sh -c "
        echo 'Yedekleme servisi basladi.';
        while true; do
          TIMESTAMP=$$(date +'%Y-%m-%d_%H-%M-%S');
          echo \"Yedekleme basliyor: sf5-backup-$${TIMESTAMP}.tar.gz\";
          
          tar -czf /backups/sf5-backup-$${TIMESTAMP}.tar.gz -C /server .;
          
          echo \"Yedekleme tamamlandi. ${BACKUP_RETENTION_DAYS} gunden eski yedekler temizleniyor...\";
          find /backups/ -type f -name '*.tar.gz' -mtime +${BACKUP_RETENTION_DAYS} -delete;
          
          echo \"Beklemeye geciliyor (${BACKUP_INTERVAL} saniye)...\";
          sleep ${BACKUP_INTERVAL};
        done
      "

networks:
  proxy:
    external: true
